name: Gradle Build with SBOM & License Reports

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Uninstall preinstalled Gradle
        run: |
          sudo rm -rf /usr/share/gradle /usr/local/gradle
          which gradle && gradle -v || echo "****************************************************Gradle removed**********************************************"

      - name: Install Gradle 7.0.2
        run: |
          wget https://services.gradle.org/distributions/gradle-7.0.2-bin.zip
          unzip -q gradle-7.0.2-bin.zip
          sudo mv gradle-7.0.2 /opt/gradle
          echo "/opt/gradle/bin" >> $GITHUB_PATH
          gradle -v

      - name: Run Gradle Build & Reports
        run: |
          chmod +x gradlew || true
          ./gradlew build || echo "Gradle build failed or skipped"
          ./gradlew dependencies --write-locks || echo "Gradle lock skipped"
          ./gradlew dependencyUpdates
          ./gradlew generateLicenseReport

      - name: List generated reports
        run: |
          echo "=== Dependency Updates ==="
          ls -l dependency-updates || echo "No dependency-updates dir"
          echo "=== License Reports ==="
          ls -l build/reports/dependency-license || echo "No license reports"

      # --- Publish Artifacts ---
      - name: Upload Outdated Dependencies (raw)
        uses: actions/upload-artifact@v4
        with:
          name: outdated-dependencies-raw
          path: dependency-updates/report.txt

      - name: Upload Outdated Dependencies (formatted)
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: outdated-dependencies-formatted
          path: outdated_dependencies_report.txt
          if-no-files-found: ignore

      - name: Upload License Reports
        uses: actions/upload-artifact@v4
        with:
          name: license-reports
          path: build/reports/dependency-license/**

#           name: sbom-result
#           path: sbom-result.txt
